---
apiVersion: "v1"
kind: "Service"
metadata:
  labels:
    app: "parking"
    version: "0.0.1-SNAPSHOT"
    group: "Houda"
  name: "parking-service"
spec:
  ports:
  - name: "http"
    port: 8081
    targetPort: 8081
  selector:
    app: "parking"
    version: "0.0.1-SNAPSHOT"
    group: "Houda"
  type: "NodePort"
---
apiVersion: "apps/v1"
kind: "Deployment"
metadata:
  labels:
    app: "parking"
    version: "0.0.1-SNAPSHOT"
    group: "Houda"
  name: "parking-service"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: "parking"
      version: "0.0.1-SNAPSHOT"
      group: "Houda"
  template:
    metadata:
      labels:
        app: "parking"
        version: "0.0.1-SNAPSHOT"
        group: "Houda"
    spec:
      containers:
      - env:
        - name: "KUBERNETES_NAMESPACE"
          valueFrom:
            fieldRef:
              fieldPath: "metadata.namespace"
        image: "koubi/parking"
        imagePullPolicy: "IfNotPresent"
        name: "parking-service"
        ports:
        - containerPort: 8081
          name: "http"
          protocol: "TCP"
